### ISSUE TITLE
Dependencies of libraries

### ISSUE THREAD

**Issue by aurangzaib048** [brave/news-aggregator#15]
We encountered an issue on 16-03-2022. 

Details:
Last night (16-March-2022), one of the dependencies of dateparser, regex was updated to version [2022.3.15](https://pypi.org/project/regex/#history). Dateparser installs regex, but without a frozen version. It seems that the newest version of regex does not like something that dateparser is doing, leading to the error we are facing. By pip installing regex==2022.3.2 before dateparser,

Solution:
We should freeze the dependency of the module/package/libraries that are being used to avoid such types of errors.

**Comment by davidegavio** [comment]
this issue has already been solved [here](https://github.com/brave/news-aggregator/commit/bb2b23d7627f7e6427b46b8116e3832377e11353)
