### ISSUE TITLE
`Toms Guide` and `Toms Hardware` should be `Tom's Guide` and `Tom's Hardware`, respectively

### ISSUE THREAD

**Issue by stephendonner** [brave/news-aggregator#171]
Summary: `Toms Guide` and `Toms Hardware` should be `Tom's Guide` and `Tom's Hardware`, respectively

Steps:
1. install latest `beta` or `nightly`
2. via `brave://flags`, enable the `Brave News v2` flag
3. click `Relaunch`
4. open a new-tab page
5. click on `Customize`
6. click on `Brave News`
7. click `Turn on Brave News`
8. search for `toms`

<img width="608" alt="Screen Shot 2022-11-02 at 5 16 19 PM" src="https://user-images.githubusercontent.com/387249/199625871-be2bbc6f-1c1b-4016-9cbf-e88b460b973a.png">

**Comment by aurangzaib048** [comment]
Fixed!
