### ISSUE TITLE
Images missing for non US locales [es-ES, es-MX, pt-BR]

### ISSUE THREAD

**Issue by Uni-verse** [brave/news-aggregator#344]
**Description:** 
Some images are missing in the top sources news feed for es-ES, es-MX, pt-BR locales

**Steps to Reproduce:** 

1. Set device system language to es-ES or es-MX or pt-BR
2. Install 1.48
3. Launch brave
4. Opt in to brave news via the NTP onboarding 
5. Check news feed

**Actual Result:**
Sources missing images in feed

Example | Example
-|-
![screenshot-1675446323117](https://user-images.githubusercontent.com/17885425/216694001-549f08bb-56c8-4c8c-a506-61678a0efe8a.png) | ![screenshot-1675442352137](https://user-images.githubusercontent.com/17885425/216694044-e85c8665-0bd3-4245-b85f-ca2559f2c994.png)

**Expected Result:**
Images should be displayed in feed

**Device Details:**
Samsung GS 21, Android 13

**Brave Version:**
`1.48.155 Chromium: 110.0.5481.77 `

**Comment by aurangzaib048** [comment]
@aekeus @mattmcalister Can you please involve QA to re-verify this. We have improved/added the images related things after this.
