### ISSUE TITLE
Check article URLs do not respond with 404 before putting in feed.json

### ISSUE THREAD

**Issue by aurangzaib048** [brave/news-aggregator#4]
We check the RSS feed url and the image urls, but we don't check the article url itself.

**Comment by mattmcalister** [comment]
Is this still a problem? Let's either add this feature or close the issue. wdyt @aurangzaib048 ?

**Comment by aurangzaib048** [comment]
We are checking this in the mentioned method. https://github.com/brave/news-aggregator/blob/8ded9005827f79614298c920aeaa5501dde9dc83/src/feed_processor_multi.py#L290
