### ISSUE TITLE
Publisher level alerting improvements

### ISSUE THREAD

**Issue by aekeus** [brave/news-aggregator#442]
Please implement publisher alerting that reports on the following issues:

  * A publisher feed becomes unavailable (!= 200 response code)
  * A publisher feed becomes out of date (difference between lastBuildDate and the latest article pubDate is greater than some value (1 day?))

**Comment by LorenzoMinto** [comment]
maybe we could also check that a source feed is well formatted: has an image, title, and whatever field we deem essential? Just to make sure of collected data quality
