### ISSUE TITLE
More Addons for Brave News Section

### ISSUE THREAD

**Issue by vinyashegde** [brave/news-aggregator#459]
People would appriciate if there are more addon for brave news like [medium.com](https://medium.com), [dev.to](https://dev.to) and many more.

![Image alt text](https://github.com/vinyashegde/dump/blob/main/Screenshot%202023-05-12%20195557.png?raw=true)

**Comment by fallaciousreasoning** [comment]
Hey @vinyashegde, you should be able to add almost any Medium blog if you do the following:
1. Go to the homepage of the Medium site (which lists all the stories)
2. Copy the URL
3. Paste it into the `Search for site, topic, or RSS feed` box
4. Click the search button
5. Subscribe to the feed it finds

Alternatively, you can subscribe via the `RSS` button on the site:
![image](https://github.com/brave/news-aggregator/assets/7678024/959e7410-6203-4a3e-a1f4-618d2906fa38)


This should work similarly for dev.to

### For the homepage:
![image](https://github.com/brave/news-aggregator/assets/7678024/29ead1ce-e7e4-4b70-ac58-1892c42e97d5)

### For a specific author:
![image](https://github.com/brave/news-aggregator/assets/7678024/d8de6ebf-a1cb-4a52-9f02-274bfd8673a7)
