### ISSUE TITLE
Testplan to verify the new regions and cover images

### ISSUE THREAD

**Issue by aurangzaib048** [brave/news-aggregator#520]
We have added four news regions.

1. de_DE
2. fr_FR
3. en_AU
4. en_IN

Currently all the newly added regions are in staging, we have to verify all the above regions in staging before going into prod.

Verify and check each region in staging follow the following steps:

- [ ] Set `one of above mentioned region` locale from your system settings
- [ ] Launch Brave using `--brave-today-host=brave-today-cdn.bravesoftware.com` flag
- [ ] Enable Brave News
- [ ] Check the default following sources feed (Are the feed coming from US)
- [ ] Scroll Down and see feed is loading proper and feed images are loading proper
- [ ] Add some custom sources

Secondly:

- [ ] Check the background color of the cover images of the publishers (Most of the publishers cover image should be visible). Ignore the rest of the publisher's cover image.

Expected Results:

- All the newly added regions have latest feeds
- Most of the cover images have the background colors

**Comment by aurangzaib048** [comment]
cc: @aekeus @petemill @mattmcalister

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.56 (23.8.4.21) Dev channel build`

Preconditions:
1. Set system locale
2. Enable staging environment for brave news in the settings menu

- Verified new regions in https://github.com/brave/news-aggregator/issues/520#issue-1839254487 are receiving feeds.
- Verified appropriate feed is downloaded per locale (de_DE, fr_FR, en_AU, en_IN).
- Verified brave news feed is shown on fresh and existing profile and user is able to add sources after upgrading.
- Verified adding sources from list and custom sources for each new region. 

<details><summary>de_DE</summary>

Example | Example | Example
-|-|-
![IMG_3451 2](https://github.com/brave/news-aggregator/assets/17885425/cf336ea4-155b-4260-83c8-9a358dfc1a64) | ![IMG_3452 2](https://github.com/brave/news-aggregator/assets/17885425/c5600720-12eb-4953-9ef1-b6a198e66b4e) | ![IMG_3453 2](https://github.com/brave/news-aggregator/assets/17885425/eeefa9fc-89f1-4de4-b942-3a771a19ed45)

</details>

<details><summary>fr_FR</summary>

![IMG_3455 2](https://github.com/brave/news-aggregator/assets/17885425/85bd4ce7-af87-4743-9b53-7c2819583ed5)

</details>

<details><summary>en_AU</summary>

Example | Example | Example
-|-|-
![IMG_3447 2](https://github.com/brave/news-aggregator/assets/17885425/d9b993e8-813c-454d-9bd2-a4d676461277) | ![IMG_3450 2](https://github.com/brave/news-aggregator/assets/17885425/1d9dc43f-4580-42c7-9f65-ac06fecd2d98) | ![IMG_3460 2](https://github.com/brave/news-aggregator/assets/17885425/f7f95896-e95f-4d6c-a0b5-65f64a78c62c)

</details>

<details><summary>en_IN</summary>

Example | Example | Example
-|-|-
![IMG_3457 2](https://github.com/brave/news-aggregator/assets/17885425/d33c4c51-3094-4ca5-96b7-3826b3a5b648) | ![IMG_3458 2](https://github.com/brave/news-aggregator/assets/17885425/feca2c7f-090f-4b2b-b2d3-b04137143b9f) | ![IMG_3459 2](https://github.com/brave/news-aggregator/assets/17885425/bccdc543-dd12-43d0-b354-059ca941b0ea)

</details>

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using version:

```
Brave	1.57.47 Chromium: 116.0.5845.96 (Official Build) (64-bit) 
Revision	180d2fdf443f9be410c38fd8c4ccfe7e99ea2b16
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Preconditions:
1. Set system locale
2. Launch app without network
3. Enable flag using `--brave-today-host=brave-today-cdn.bravesoftware.com` for command line string in the QA settings menu
4. Re-launch app with network

- Verified new regions in https://github.com/brave/news-aggregator/issues/520#issue-1839254487 are receiving feeds.
- Verified appropriate feed is downloaded per locale (de_DE, fr_FR, en_AU, en_IN).
- Verified adding sources from list and custom sources for each new region. 

<details><summary>de_DE</summary>

![Screenshot 2023-08-16 at 5 49 46 PM](https://github.com/brave/news-aggregator/assets/17885425/73ae89e3-40e6-43ba-93d6-792bbba7289c) | ![Screenshot 2023-08-16 at 5 50 40 PM](https://github.com/brave/news-aggregator/assets/17885425/3a807adc-3010-47cc-b928-c10b1b53436d)

</details>

<details><summary>fr_FR</summary>

![Screenshot 2023-08-16 at 5 27 47 PM](https://github.com/brave/news-aggregator/assets/17885425/d0f0216b-59e9-464f-8f50-7a00b856cad0)
![Screenshot 2023-08-16 at 5 28 01 PM](https://github.com/brave/news-aggregator/assets/17885425/d140e081-c6fc-4fb2-8a76-3768b113ca76)

</details>

<details><summary>en_AU</summary>

![Screenshot 2023-08-16 at 4 19 24 PM](https://github.com/brave/news-aggregator/assets/17885425/60a71f3d-c367-4a25-86d2-921717de99c7)
-|-
![Screenshot 2023-08-16 at 4 13 24 PM](https://github.com/brave/news-aggregator/assets/17885425/41d70afa-add9-40b6-9670-cf467b911197)
![Screenshot 2023-08-16 at 4 13 02 PM](https://github.com/brave/news-aggregator/assets/17885425/f2aac85a-7c38-42c6-9c3b-4b967b939dd3)

</details>

<details><summary>en_IN</summary>

![Screenshot 2023-08-16 at 4 39 29 PM](https://github.com/brave/news-aggregator/assets/17885425/9c0b763f-e1cd-4b5f-ac93-a114c1fefe16)
![Screenshot 2023-08-16 at 4 39 58 PM](https://github.com/brave/news-aggregator/assets/17885425/b872f76b-193f-42fa-8fe1-7c665fe39372)

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.57.47 Chromium: 116.0.5845.96 (Official Build) (x86_64)
-- | --
Revision | 180d2fdf443f9be410c38fd8c4ccfe7e99ea2b16
OS | macOS Version 11.7.9 (Build 20G1426)
```

de_DE
fr_FR
en_AU
en_IN

**Comment by stephendonner** [comment]
@aurangzaib048 @mattmcalister @petemill forgot to mention that the string `Top News` doesn't appear translated in the above-tested languages/regions/locales, just FYI.  Not sure, but seems like that's a client-side issue?

**Comment by Uni-verse** [comment]
> @aurangzaib048 @mattmcalister @petemill forgot to mention that the string `Top News` doesn't appear translated in the above-tested languages/regions/locales, just FYI. Not sure, but seems like that's a client-side issue?

I see the same thing on Android (1.57.x) I think this is client side since its the header on the card. 

![Screenshot 2023-08-22 at 9 34 48 AM](https://github.com/brave/news-aggregator/assets/17885425/8000ef97-9a4d-4f56-940b-7a5e1bfb9ccb)

**Comment by aurangzaib048** [comment]
Completed
