### ISSUE TITLE
Cron for better uptime health endpoint

### ISSUE THREAD

**Issue by porteron** [brave/news-aggregator#546]
- [ ] Create a script for pulling in the latest publish timestamp for each region `.json` source.
  - [ ] If all sources have been refreshed within the last 3 hours then return success status
  - [ ] If some regions have expired then return a warning status code
  - [ ] If json file is completely unavailable then return an error status.
  
*I assume Betteruptime is able to distinguish warning vs error states. I will research this more*

cc @aurangzaib048

**Comment by aurangzaib048** [comment]
Completed
