### ISSUE TITLE
topics_news JSON needs publisher_id

### ISSUE THREAD

**Issue by petemill** [brave/news-aggregator#563]
Please add publisher_id to `topics_news.[locale].json`. At the moment it only has publisher_name, and it would be good to do an exact match.

**Comment by aurangzaib048** [comment]
Do we need to add `publisher_id` to add in the above mentioned file?

cc: @LorenzoMinto

**Comment by LorenzoMinto** [comment]
What are you referring to @aurangzaib048?

**Comment by aurangzaib048** [comment]
`topics_news.[locale].json` generated in the clustering services but the articles contains the name of the publisher not the ID, but we need publisher id as well. I think it will be fixed in the clustering services. What do you think? @LorenzoMinto

**Comment by LorenzoMinto** [comment]
Yes, it clearly should be fixed in the clustering service. I created an issue there, can you create the PR? Should be a one-liner change.

**Comment by aurangzaib048** [comment]
PR: https://github.com/brave/news-topic-clustering/pull/159

**Comment by aurangzaib048** [comment]
Merged into https://github.com/brave/news-topic-clustering staging, it will take sometime to reflect the changes.
