### ISSUE TITLE
Several favicons for publishers in the customise page have visual glitches

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/news-aggregator#568]
Similar to https://github.com/brave/news-aggregator/issues/168

Some of the cover images look pixelated/distorted or have a weird background/foreground color combination. Some examples attached 

<img width="653" alt="Screenshot 2023-10-06 at 14 05 25" src="https://github.com/brave/news-aggregator/assets/13190144/1352dbf9-18f8-46c9-8178-bac3bec5d2e1">
<img width="665" alt="Screenshot 2023-10-06 at 14 04 37" src="https://github.com/brave/news-aggregator/assets/13190144/46472435-ad10-4f4c-8145-3e3bbb20b5d7">
<img width="236" alt="Screenshot 2023-10-06 at 14 04 30" src="https://github.com/brave/news-aggregator/assets/13190144/d866049c-4264-4e53-8d2b-029113b4082a">
<img width="236" alt="Screenshot 2023-10-06 at 14 04 53" src="https://github.com/brave/news-aggregator/assets/13190144/5a87c496-d84e-4fca-814c-360f46deb792">

**Comment by LorenzoMinto** [comment]
Duplicate of https://github.com/brave/news-aggregator/issues/665

**Comment by aurangzaib048** [comment]
Available in staging.

**Comment by aurangzaib048** [comment]
Deployed.
