### ISSUE TITLE
Brave News Source Domains

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/news-aggregator#58]
At the moment, it's a bit inconvenient to consume the `Domain` field from `sources.json`, as the schemes aren't included for the default sources file (`sources.csv`) but they are in the Japanese `sources.ja.csv` file.

It would be nice if we could standardise on one format (my preference would be for `https://{domain}.{tld}/` over `{domain}.{tld}` because it's already a valid URL).

In addition, many of the domains require a redirect to get the correct origin. For example:
- `economist.com` ==> `https://www.economist.com/`
- `theguardian.com` ==> `https://www.theguardian.com/`
- `theatlantic.com` ==> `https://www.theatlantic.com/`

Note: These are all technically different origins.

I notice that there's also a destination domains column in the CSV. However, this column can have multiple urls, and it's not immediately obvious which one to use. For example `finance.yahoo.com` has several destination domains `www.barrons.com;www.marketwatch.com;www.investors.com;finance.yahoo.com;www.investopedia.com` and they are not all equivalent (https://www.barrons.com/an-article does not imply finance.yahoo.com/an-article).

**Note:** Some domains don't start with a `www.` and we should respect that. Examples are
- `lifehacker.com` ==> `https://lifehacker.com/`
- `knowyourmeme.com` ==> `https://knowyourmeme.com/`

**Comment by fallaciousreasoning** [comment]
Just reopening until we have the proper urls landed :smile:

**Comment by aurangzaib048** [comment]
@fallaciousreasoning  Can you confirm that this is fixed?

**Comment by fallaciousreasoning** [comment]
Yeah, its is! Thanks @aurangzaib048
