### ISSUE TITLE
Remove unused sources.ja.csv and sources.csv files

### ISSUE THREAD

**Issue by aekeus** [brave/news-aggregator#614]
sources.ja.csv  and sources.csv early versions (When we had only have 2 regions) of the Japan and US feeds but the new ones are ja_JP and en_US.

**Comment by mattmcalister** [comment]
can we confirm the feed files generated from those csv's either don't exist or are never fetched before removing these?

**Comment by aekeus** [comment]
Yes, we will test this before removing them

**Comment by aurangzaib048** [comment]
cc: @petemill @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
So there is one case where they could be fetched:

If a user hasn't updated Brave since we launched the new `sources.global.csv` to stable (I think about a year ago now) then we fetch the old feeds to migrate them over.

Maybe it's been long enough that we can remove that code now?

**Comment by aurangzaib048** [comment]
Completed.
