### ISSUE TITLE
News should be changed to RSS feed,  No Custom News sources. That's why people don't like Brave.

### ISSUE THREAD

**Issue by Pantyhose-X** [brave/news-aggregator#663]
Discover is of no value to many people right now, a waste of time.

Suggest supporting RSS to make Discover valuable.

RSS Subscribe sources
https://raw.githubusercontent.com/brave/news-aggregator/master/sources/sources.en_US.csv

**Comment by aurangzaib048** [comment]
Hi @Pantyhose-X, To add the custom RSS feeds, there is option in Brave News config, you can have look there.
Thanks for reaching out and sharing your concern.
