### ISSUE TITLE
Create global sources file

### ISSUE THREAD

**Issue by aurangzaib048** [brave/news-aggregator#81]
From matt: related, just eyeballing the data, seems to me that the average filesize for each sources json file is going to be around 25kb. the US is bigger but most of them should be in that range or even smaller. so, if that’s true, it means we probably have a ceiling of about 20 sources files which would get us to 500k before we need to optimize. it could take us another 6 months to a year before we have 20 sources files. so, filesize probably shouldn’t be a blocker to making a single sources.global.json file if that’s the most sensible thing to do in terms of architecture and usability.

https://bravesoftware.slack.com/archives/CU56GUJ1H/p1661532666592129?thread_ts=1661273626.869639&cid=CU56GUJ1H

**Comment by petemill** [comment]
Expected output from my client-side point of view (note `locales` field):

```json
[  
{
    "enabled": false,
    "publisher_name": "kottke.org",
    "category": "Culture",
    "destination_domains": [
      "kottke.org"
    ],
   "locales": [
       {
          "lang": "en",
          "region": "US"
       },
       {
          "lang": "en",
          "region": "GB"
       }
    ],
    "site_url": "kottke.org",
    "feed_url": "https://feeds.kottke.org/main",
    "score": -0.16,
    "publisher_id": "e44e7aea7e34bb52c5baf7c5b23ff2e887db242036e797c91e424b25267aba22"
  },
  {
    "enabled": false,
    "publisher_name": "mindbodygreen",
    "category": "Health",
    "destination_domains": [
      "www.mindbodygreen.com"
    ],
   "locales": [
       {
          "lang": "ja",
          "region": "jp"
       }
    ],
    "site_url": "mindbodygreen.com",
    "feed_url": "https://www.mindbodygreen.com/rss/feed.xml",
    "score": 0.87,
    "publisher_id": "f930d64e9313dfb00fca6790d58eee8a2adc123fe369215fac755631e56438b7"
  }
]
```

_note: not real data!_

**Comment by aurangzaib048** [comment]
[From jay]
"locales": ["en_US", "en_GB"]

**Comment by aurangzaib048** [comment]
Completed.
