### ISSUE TITLE
News View Options

### ISSUE THREAD

**Issue by WHiZSTA** [brave/news-aggregator#84]
On the left add options where you can select a view including by category or specific feeds. Add a sort option of random, newest first, oldest first. Add a search option that searches the titles of the articles for your selected view.

**View**
- All Items
- Top News
- Entertainment
- Business
- etc
- **Sources**
  - feed1.com
  - feed2.com
  - feed3.com

**Sort By**: Random
**Search**: None

**Comment by aurangzaib048** [comment]
We are working on Brave News 2.0, which will address all the things you have mentioned here and in other issues. Stay tuned and keep checking. I hope you are enjoying using Brave Browser.

**Comment by WHiZSTA** [comment]
> We are working on Brave News 2.0, which will address all the things you have mentioned here and in other issues. Stay tuned and keep checking. I hope you are enjoying using Brave Browser.

That's great to hear, i can't wait! Is there an outline somewhere showing what all is coming, and/or a way to try/test things out like the beta or nightly channels?

**Comment by aurangzaib048** [comment]
Currently, we are working and testing these things in our internal release, but hopefully it will be available on the nightly release soon.
